# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-testimages/gcb-docker-gcloud:v20210331-c732583'
    env:
    - GIT_TAG=$_PULL_BASE_REF
    - GIT_COMMIT=$_PULL_BASE_SHA
    args:
    - '-c'
    - |
      ./hack/init-buildx.sh \
      && make push-all
